name: Go

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Update to v4
      with:
        ref: main  # Update branch name if necessary

    - name: Set up Go
      uses: actions/setup-go@v5  # Update to v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
