name: Go

on:
  push:
    branches: 
      - main
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  docker-publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')  # Execute only if tag is pushed
    steps:
    # - name: Check out the repository
    #  uses: actions/checkout@v4

    # - name: Log in to DockerHub
    #  run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.rsteele21 }}" --password-stdin

    - name: Build Docker image
      run: docker build -t rsteele21/actions:latest .

    #- name: Publish Docker image
    #  run: docker push rsteele21/actions:latest
